name: debug
on: [push]
jobs:
  build:
    runs-on: macos-latest
    if: |
      contains(github.event.head_commit.message, '[debug]')
    steps:
    - uses: actions/checkout@v3
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
